company/urls.py
from django.conf.urls import url

from company.views import (DashboardView, CompanySignUpView, ItemCreateView,
                           ItemUpdateView, ItemDeleteView, ItemsListView)

app_name = "company"

urlpatterns = [
    url(r'^register/', CompanySignUpView.as_view(), name="register"),
    url(r'^dashboard/', DashboardView.as_view(), name="dashboard"),
    url(r'^item/$', ItemCreateView.as_view(), name="create_item"),
    url(r'^item/(?P<pk>[\d]+)/$', ItemUpdateView.as_view(), name="update_item"),
    url(r'^item/(?P<pk>[\d]+)/$', ItemDeleteView.as_view(), name="delete_item"),

    url(r'^items/$', ItemsListView.as_view(), name="list_items"),
]

customer/urls.py
from django.conf.urls import url
from customer.views import CustomerSignUpView, BrowseView, CustomerUpdateView

app_name = "customer"

urlpatterns = [
    url(r'^register/', CustomerSignUpView.as_view(), name="register"),
    url(r'^browse/', BrowseView.as_view(), name="browse"),
    url(r'^update/', CustomerUpdateView.as_view(), name="update"),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.core.urlresolvers import reverse
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test

from ecommerce.views import HomeView, LandingPageView
from ecommerce import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^welcome/$', LandingPageView.as_view(), name="landing"),

    url(r'^admin/', admin.site.urls),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^auth/', include('django.contrib.auth.urls', namespace="auth")),

    url(r'^customer/',
        include('customer.urls', namespace='customer')),

    url(r'^company/',
        include('company.urls', namespace='company')),

    url(r'^company/',
        include('component.urls', namespace='component')),
]

company/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.validators import MinLengthValidator

from account import models as account_models
from customer import models as customer_models

class Company(account_models.Account):
    name = models.CharField(max_length=50)

    PIB = models.CharField(max_length=9,
                           validators=[MinLengthValidator(9, message="PIB must be exactly 9 chars long.")],
                           unique=True)

    LK = models.CharField(max_length=50)
    uID = models.CharField(max_length=50, unique=True, null=True)

    class Meta:
        verbose_name_plural = 'companies'


    def __unicode__(self):
        return '%s' % (self.name,)

company/forms.py
from django import forms
from django_countries.fields import CountryField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from company import models



class CompanyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)

        self.fields['LK'].label = 'Owner\'s personal ID number:'

    class Meta:
        model = models.Company
        exclude = ('user', 'uID')

company/views.py
from django.db import transaction
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import (FormView, CreateView, UpdateView,
                                       DeleteView)
import autocomplete_light

from account.forms import UserForm
from company.forms import CompanyForm
from component.models import Available
from component.forms import AvailableForm



class DashboardView(TemplateView):
    template_name = 'company/dashboard.html'



class CompanySignUpView(FormView):
    template_name = 'company/signup.html'
    success_url = '/'

    # override the default form insertion,
    # we're doing manual work with sending custom forms
    # NOTE: All this should be replaced with inline formset at one point
    def get_form(self):
        return None

    def get_context_data(self, *args, **kwargs):
        """
        Load the appropriate forms into context.
        If they're already in, it means we're getting back bound forms with
        validation errors.
        """
        context = super(CompanySignUpView, self).get_context_data(*args, **kwargs)

        if('user_form' not in context):
            context['user_form'] = UserForm(prefix="user")

        if('company_form' not in context):
            context['company_form'] = CompanyForm(prefix="company")

        return context


    def post(self, *args, **kwargs):
        user_form = UserForm(self.request.POST, prefix="user")
        company_form = CompanyForm(self.request.POST, prefix="company")

        if user_form.is_valid() and company_form.is_valid():
            return self.form_valid(user_form, company_form)
        else:
            return self.render_to_response(self.get_context_data(user_form=user_form, company_form=company_form))



    def form_valid(self, form, company_form):
        with transaction.atomic():
            company = company_form.save(commit=False)
            user = form.save()
            company.user = user
            company.save()

        return super(CompanySignUpView, self).form_valid(form)



class ItemCreateView(CreateView):
    model = Available
    form_class = AvailableForm

    template_name = 'company/create.html'



class ItemUpdateView(UpdateView):
    model = Available
    form = autocomplete_light.modelform_factory(Available, fields=('component',))



class ItemDeleteView(DeleteView):
    model = Available



class ItemsListView(ListView):
    model = Available

templates/company/create.html
{% extends 'customer/browse.html' %}
{% load crispy_forms_tags %}

{% block data %}
<!--<form action="{% url 'customer:update' %}" method="post">-->
  <!--{% csrf_token %}-->
  <!--<div class="input-group">-->
    <!--<a href="#">New component</a>-->
    <!--{{ form.component|as_crispy_field }}-->
  <!--</div>-->
  <!--{{ form.n_available|as_crispy_field }}-->
  <!--<input class="btn btn-primary" type="submit" value="Update"></input>-->
  <!--<a class="btn btn-default" href="{% url 'customer:browse' %}">Cancel</a>-->
<!--</form>-->

{% crispy form %}
{% endblock %}

templates/company/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block extrastyles %}
{{ block.super }}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/browse-sidebar.css' %}" rel="stylesheet">
<link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">
{% endblock %}


{% block extrascripts %}
{% endblock %}

{% block sidebar %}
  {% include 'company/sidebar.html' %}
{% endblock %}

{% block content %}
  <div class="row" style="margin-top: 20px">
    {% if companies %}
      <div class="col-md-offset-5 col-md-6 well">
    {% else %}
      <div class="col-md-offset-3 col-md-8 well">
    {% endif %}
    </div>
  </div>
{% endblock %}

templates/company/sidebar.html
{% load static %}

<!-- Sidebar -->
<div id="sidebar-categories" class="sidebar">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
          Operations
        </li>
        <li>
          <a href="{% url 'company:create_item' %}">Create item</a>
          <a href="{% url 'company:list_items' %}">List items</a>
          {#<!--<a href="{% url 'company:reservations' %}">Reservations</a>-->#}
          {#<!--<a href="{% url 'company:orders' %}">Orders</a>-->#}
        </li>
    </ul>
</div>

templates/company/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <h1 class="text-center">Register</h1>
    <form action="{% url 'company:register' %}" method="post" />
      {% csrf_token %}
      {{ form.non_field_errors }}
      <h2>Account details</h2>
      {{ user_form|crispy }}

      <h2>Company details</h2>
      {{ company_form|crispy }}

      <input class="btn btn-primary" type="submit" value="Register"></input>
    </form>
  </div>
</div>
{% endblock %}