company/urls.py
from django.conf.urls import url

from company.views import (DashboardView, CompanySignUpView, ItemCreateView,
                           ItemUpdateView, ItemDeleteView, ItemsListView)

app_name = "company"

urlpatterns = [
    url(r'^register/', CompanySignUpView.as_view(), name="register"),
    url(r'^dashboard/', DashboardView.as_view(), name="dashboard"),
    url(r'^item/$', ItemCreateView.as_view(), name="create_item"),
    url(r'^item/(?P<pk>[\d]+)/$', ItemUpdateView.as_view(), name="update_item"),
    url(r'^item/(?P<pk>[\d]+)/$', ItemDeleteView.as_view(), name="delete_item"),

    url(r'^items/$', ItemsListView.as_view(), name="list_items"),
]

customer/urls.py
from django.conf.urls import url
from customer.views import CustomerSignUpView, BrowseView, CustomerUpdateView

app_name = "customer"

urlpatterns = [
    url(r'^register/', CustomerSignUpView.as_view(), name="register"),
    url(r'^browse/', BrowseView.as_view(), name="browse"),
    url(r'^update/', CustomerUpdateView.as_view(), name="update"),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.core.urlresolvers import reverse
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test

from ecommerce.views import HomeView, LandingPageView
from ecommerce import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^welcome/$', LandingPageView.as_view(), name="landing"),

    url(r'^admin/', admin.site.urls),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^auth/', include('django.contrib.auth.urls', namespace="auth")),

    url(r'^customer/',
        include('customer.urls', namespace='customer')),

    url(r'^company/',
        include('company.urls', namespace='company')),

    url(r'^company/',
        include('component.urls', namespace='component')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>ECommerce {% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
  {% block extrastyles %}
  {% endblock %}
</head>
<body>
  {% include 'navbar.html' %}

  {% block sidebar %}
  {% endblock %}

  <div id="content" class="container-fluid">
    {% block content %}
    {% endblock %}
  </div>

  <script src="{% static 'js/jquery.js' %}"></script>
  {% include 'autocomplete_light/static.html' %}
  {% block extrascripts %}
  {% endblock %}
</body>
</html>

templates/landing.html
{% load static %}

<!DOCTYPE html>
<html class="full" lang="en">
<!-- Make sure the <html> tag is set to the .full CSS class. Change the background image in the full.css file. -->

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>The Big Picture - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/the-big-picture.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Computer Components</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                      <a href="{% url 'customer:register' %}">Register as a customer</a>
                    </li>
                    <li>
                      <a href="{% url 'company:register' %}">Register as a company</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-12">
                <h1>We sell computer equipment</h1>
                <p>However, we're reserved to premium customers only. If you're
                a customer, please <a href="{% url 'auth:login' %}">log in</a>. If you'd
                like to become one, or you represent a company you can register below.</p>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/navbar.html
<nav class="navbar navbar-default navbar-static-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button> <a class="navbar-brand" href="{% url 'home' %}">Computer Components</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="{% url 'customer:browse' %}">Browse</a>
        </li>


        <!--<li>-->
          <!--<a href="#">Link</a>-->
        <!--</li>-->


        <!--<li class="dropdown">-->
           <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li>-->
              <!--<a href="#">Action</a>-->
            <!--</li>-->
            <!--<li>-->
              <!--<a href="#">Another action</a>-->
            <!--</li>-->
            <!--<li>-->
              <!--<a href="#">Something else here</a>-->
            <!--</li>-->
            <!--<li class="divider">-->
            <!--</li>-->
            <!--<li>-->
              <!--<a href="#">Separated link</a>-->
            <!--</li>-->
            <!--<li class="divider">-->
            <!--</li>-->
            <!--<li>-->
              <!--<a href="#">One more separated link</a>-->
            <!--</li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>


      <!--<form class="navbar-form navbar-left" role="search">-->
        <!--<div class="form-group">-->
          <!--<input type="text" class="form-control" />-->
        <!--</div>-->
        <!--<button type="submit" class="btn btn-default">-->
          <!--Submit-->
        <!--</button>-->
      <!--</form>-->


      <ul class="nav navbar-nav navbar-right">
        {% if user.is_anonymous %}
        <li>
          <a href="{% url 'auth:login' %}?next={% url 'home' %}">Login</a>
        </li>
        {% else %}
        <li>
          <p class="navbar-text">Logged in as {{ user.username }}</p>
        </li>
        <li>
          <a href="{% url 'auth:logout' %}?next={% url 'home' %}">Logout</a>
        </li>
        {% endif %}

        <!--<li class="dropdown">-->
           <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li>-->
              <!--<a href="#">Action</a>-->
            <!--</li>-->
            <!--<li>-->
              <!--<a href="#">Another action</a>-->
            <!--</li>-->
            <!--<li>-->
              <!--<a href="#">Something else here</a>-->
            <!--</li>-->
            <!--<li class="divider">-->
            <!--</li>-->
            <!--<li>-->
              <!--<a href="#">Separated link</a>-->
            <!--</li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>
    </div>
  </div>
</nav>